[package]
name = "gpu-plugin-controller"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gpu-plugin-controller"
path = "src/main.rs"

[dependencies]
anyhow = "1"
api = { workspace = true }
apimachinery = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
client-rs = { workspace = true }
gpu-plugin-api = { path = "../api" }
logger = { workspace = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1"
