apiVersion: v1
kind: Pod
metadata:
  name: gpu-plugin-controller
  namespace: kube-system
  labels:
    component: gpu-plugin-controller
spec:
  hostNetwork: true
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  containers:
    - name: gpu-plugin-controller
      image: ghcr.io/stevenissleepy/gpu-plugin-controller:latest
      command:
        - gpu-plugin-controller
      args:
        - --api-server=$(MINIK8S_APISERVER)
        - --runner-image=ghcr.io/stevenissleepy/gpujob-runner:latest
